# Generated by Django 4.1.2 on 2023-08-24 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debit_app', '0003_alter_account_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('appr_status', models.BooleanField()),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debit_app.card')),
            ],
        ),
    ]
